name: Run Tests and Generate Allure Report

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Python (or your test environment; this example uses Python)
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # Install dependencies
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          

      # Run tests and generate Allure results
      - name: Run tests and generate Allure report
        run: |
          pytest  # This generates the results in allure-results folder

      # Upload Allure results as an artifact (you can download them later)
      - name: Upload Allure results
        uses: actions/upload-artifact@v3
        with:
          name: allure-results
          path: allure-results/

      # Optional: Generate the Allure report (HTML) from the results
      - name: Generate Allure HTML report
        run: |
          allure generate allure-results --clean -o allure-report  # Generate the HTML report

      # Upload the generated Allure HTML report (so it can be downloaded as an artifact)
      - name: Upload Allure HTML report
        uses: actions/upload-artifact@v3
        with:
          name: allure-html-report
          path: allure-report/  # Path to the generated HTML report
