name: Playwright Tests

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  test:
    timeout-minutes: 60
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install allure-pytest
      - name: Verify Allure installation
        run: allure --version
      - name: Ensure browsers are installed
        run: python -m playwright install --with-deps

      - name: Run your tests
        run: |
          python -m pytest --tracing=on -rA --quiet --verbose --alluredir=allure-results --video=retain-on-failure --full-page-screenshot
      

      # Generate Allure HTML report
      - name: Generate Allure HTML report
        run: |
          allure generate allure-results --clean -o allure-report  # Generates the HTML report from allure-results
      - name: List contents of allure-report directory
        run: ls -la allure-report/ # Verify that the index.html file is created

      - name: Upload Allure raw results as artifact
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: allure-results/ # Upload raw Allure results (JSON, XML files)

      - name: Upload Allure HTML report as artifact
        uses: actions/upload-artifact@v4
        with:
          name: allure-html-report
          path: allure-report/ # Upload the generated HTML report, including index.html
