name: Playwright Tests

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  test:
    timeout-minutes: 300
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Ensure browsers are installed
      - name: Ensure browsers are installed
        run: python -m playwright install --with-deps

      # Run your tests with Allure results
      - name: Run your tests
        run: python -m pytest --tracing=retain-on-failure -rA --quiet --verbose --alluredir=allure-results --clean-alluredir --video=retain-on-failure --full-page-screenshot

      # Upload Allure results as artifacts for use within the workflow
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-traces
          path: allure-results/

      # Generate Allure HTML report
      - name: Generate Allure HTML report
        run: |
          allure generate allure-results --clean -o allure-report

      # Deploy Allure HTML report to GitHub Pages
      - name: Deploy Allure report to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages # GitHub Pages branch
          folder: allure-results # Path to the generated Allure report folder
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # GitHub token for authentication
