name: Playwright Tests
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
jobs:
  test:
    timeout-minutes: 300
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Ensure browsers are installed
        run: python -m playwright install --with-deps
      - name: Run your tests
        run: python -m pytest --tracing=retain-on-failure -rA --quiet --verbose --alluredir=allure-results --clean-alluredir --video=retain-on-failure --full-page-screenshot

      - name: Upload Allure results
        uses: actions/upload-artifact@v3
        with:
          name: allure-results
          path: allure-results/

      # Optional: Generate Allure HTML report
      - name: Generate Allure HTML report
        run: |
          allure generate allure-results

      # Upload the generated Allure HTML report
      - name: Upload Allure HTML report
        uses: actions/upload-artifact@v3
        with:
          name: allure-html-report
          path: allure-results/
