name: Playwright Tests

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  test:
    timeout-minutes: 300
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

        # Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.12"

        # Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

        # Ensure browsers are installed for Playwright
    - name: Ensure browsers are installed
      run: python -m playwright install --with-deps

        # Run your tests with Allure results
    - name: Run your tests
      run: |
        python -m pytest --tracing=retain-on-failure -rA --quiet --verbose --alluredir=allure-results --clean-alluredir --video=retain-on-failure --full-page-screenshot

        # Upload Allure results as artifacts for use within the workflow
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-traces
        path: allure-results/

        # Generate Allure HTML report
    - name: Generate Allure HTML report
      run: |
          allure generate allure-results

        # Upload the Allure HTML report as an artifact
    - name: Upload Allure HTML report as artifact
      uses: actions/upload-artifact@v4
      with:
        name: allure-html-report
        path: allure-report/index.html # Upload the generated HTML report
