name: Playwright Tests

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  test:
    timeout-minutes: 60
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install allure-pytest
      - name: Ensure browsers are installed
        run: python -m playwright install --with-deps

      - name: Run your tests
        run: |
          python -m pytest --tracing=on -rA --quiet --verbose --alluredir=allure-results --video=retain-on-failure --full-page-screenshot
      # Generate Allure HTML report
      - name: Generate Allure HTML report
        run: |
          python -m allure generate allure-results --clean -o allure-report
      # Upload Allure HTML report as artifact
      - name: Upload Allure HTML report as artifact
        uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: allure-results
          path: allure-results/
      # Upload Allure HTML report as artifact
      - name: Upload Allure HTML report as artifact
        uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: allure-html-report
          path: allure-report/