name: Playwright Tests

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  test:
    timeout-minutes: 60
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install allure-pytest  # Ensure allure-pytest is installed

      # Ensure browsers are installed
      - name: Ensure browsers are installed
        run: python -m playwright install --with-deps

      # Run tests with Allure results
      - name: Run tests
        run: |
          python -m pytest --tracing=on -rA --quiet --verbose --alluredir=allure-results --clean-alluredir --video=retain-on-failure --full-page-screenshot

      # Generate Allure HTML report
      - name: Generate Allure HTML report
        run: |
          allure generate allure-results --clean -o allure-report

      # Upload Allure HTML report as artifact
      - name: Upload Allure HTML report as artifact
        uses: actions/upload-artifact@v4
        with:
          name: allure-html-report
          path: allure-report/
